# Generated by Django 2.2.2 on 2019-06-19 22:53

from django.db import migrations


def add_genres(apps, schema_editor):
    genre_names = [
        'Action',
        'Adventure',
        'Animation',
        'Children',
        'Comedy',
        'Crime',
        'Documentary',
        'Drama',
        'Fantasy',
        'Film-Noir',
        'Horror',
        'Musical',
        'Mystery',
        'Romance',
        'Sci-Fi',
        'Thriller',
        'War',
        'Western'
    ]

    Genre = apps.get_model("restapi", "Genre")
    for name in genre_names:
        new_genre = Genre(name=name)
        new_genre.save()

class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_genres)
    ]
