# Generated by Django 2.2.2 on 2019-06-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20190620_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='tmbd_id',
            new_name='tmdb_id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='restapi.Movie'),
        ),
    ]
